### ISSUE TITLE
ESP32CAM can't see CAMERA MODEL in `make menuconfig'

### ISSUE THREAD

**Issue by NoamGit** [m5stack/m5stack-cam-psram#19]
Hi,
### Background
I followed your guidelines and set the 'esp-idf' environment. I've tried to flash the `hello_world` program and it worked. Now I want to proceed to step 3 and to configure the camera, however, it seems like it is not recognized as there is no option in the `make menuconfig`
![image](https://user-images.githubusercontent.com/13464827/60864925-93e50a80-a22d-11e9-97b1-95727551bee1.png)

### Question
Is there any chance that flashing the program changed the firmware and now the camera module is disabled? If so, how can I revert?

### Other
I use Ubuntu 16.04 with Eclipse C/C++ and a python 3.6 environment
the output of the `hello_world` is 
```
Hello World!
This is ESP32 chip with 2 CPU cores, WiFi/BT/BLE, silicon revision 1, 4MB external flash
Restarting in 10 seconds...
Restarting in 9 seconds...
Restarting in 8 seconds...
Restarting in 7 seconds...
Restarting in 6 seconds...
```

**Comment by EeeeBin** [comment]
Try go to Camera project dir, like **_m5stack-cam-psram/wifi/wifi_ap_**, then run `make menuconfig`
