### ISSUE TITLE
not working on M5Camera TELEC compatible ver.

### ISSUE THREAD

**Issue by skishida** [m5stack/m5stack-cam-psram#2]
By reference [this tweet from @ M5Stack](https://twitter.com/M5Stack/status/1074283145539842050), some pin configuration on `m5stack-cam-psram/main/main.c` should need to change.

|LINE|BEFORE|AFTER|
|-|-|-|
|23| #define CAM_PIN_SIOD    25| #define CAM_PIN_SIOD    **22**|
|35| #define CAM_PIN_VSYNC   22| #define CAM_PIN_VSYNC   **25**|

**Comment by EeeeBin** [comment]
thanks, now add it in readme
