### ISSUE TITLE
issue with "make"  /uart/components/esp32-camera/driver/twi.c', needed by `driver/twi.o'.

### ISSUE THREAD

**Issue by liubomyr-kozak** [m5stack/m5stack-cam-psram#25]
module: ESP32CAM
sdkconfig: default
tested code: https://github.com/m5stack/m5stack-cam-psram/tree/master/uart

ESP-IDF v3.2.3-167-g3b7777e22-dirty 2nd stage bootloader
when try make flash getting error make[1]: *** No rule to make target `/......./m5stack-cam-psram/uart/components/esp32-camera/driver/twi.c', needed by `driver/twi.o'.  Stop.
make: *** [component-esp32-camera-build] Error 2

**Comment by chidea** [comment]
according to [this esp32-homekit-camera issue](https://github.com/maximkulkin/esp32-homekit-camera/issues/57), go to `menuconfig > Component config > driver configurations > RTCI0 configuration` and enable it, save and build.

**Comment by liubomyr-kozak** [comment]
work for me, thanks
