### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by jbkim** [m5stack/m5stack-cam-psram#5]
I set up the esp-idf and compiled this code but got below error as below. 
Is there any requirement to compile?

/m5stack-cam-psram-ModeA/main/main.c:16:29: fatal error: esp_http_server.h: No such file or directory
compilation terminated.
make[1]: *** [main.o] Error 1
make: *** [component-main-build] Error 2

**Comment by EeeeBin** [comment]
This needs to be updated with the new esp-idf to the latest version :)

**Comment by jbkim** [comment]
Thanks @sakabin
