### ISSUE TITLE
black screen on start

### ISSUE THREAD

**Issue by machinehistories** [m5stack/m5stack-cam-psram#6]
I am having an issue with the new fisheye camera. I plugged it in and accessed the ap wifi but then when I go to 196.128.4.1 it is just showing a black screen with a small white square in the middle. I downloaded the firmware and reloaded it but it does the same thing. Can anybody tell me what might be the issue.

**Comment by EeeeBin** [comment]
Does it work when you get the camera at the beginning?

**Comment by machinehistories** [comment]
No when I first purchased it the screen was black with small white square.
I have successfully used my camera model A but I haven't been able to get
the model F to work. When I reinstall firmware it looks exactly the same
which is to say it has a black screen and small white square.

**Comment by EeeeBin** [comment]
If this problem has not been resolved, please contact the seller to change
a new one

machinehistories <notifications@github.com> 于2019年3月19日周二 下午2:59写道：

> No when I first purchased it the screen was black with small white square.
> I have successfully used my camera model A but I haven't been able to get
> the model F to work. When I reinstall firmware it looks exactly the same
> which is to say it has a black screen and small white square.
>
